### ISSUE TITLE
[INF-18-40] Fix root route test

### ISSUE THREAD

**Issue by phillip055** [yearn/yearn-caching-api#40]
Currently when we run tests, the test fails, here are the reasons.

* [ ] response is not accurate
* [ ] teardown is causing timeouts, need to be able to handle this properly

**Comment by 0xkofee** [comment]
@phillip055 https://github.com/yearn/yearn-api/pull/43

**Comment by 0xkofee** [comment]
@phillip055 do you know anyone that can help merge this? thx

**Comment by phillip055** [comment]
Closing as this #43, is merged
